spring.application.name=apirest
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/apirest
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=3E6G3f4oQfyFb3kgmF6tqL8a2Ow5mMObpgR4H1fw6u0DN+5oUpy2nB7vVQdK9eqUoDpFTZoxWWoH2u88TfIu0Q==
# 1 hora (em ms)
jwt.expiration-ms=3600000
